on:
  push:
    branches:
      - main # Change this to your default branch if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd th-ws
          yarn install

      - name: Build site
        run: |
          cd th-ws
          yarn build

      - name: Deploy to GitHub Pages
        env:
          USE_SSH: false
          GIT_USER: ${{ github.actor }}
          CURRENT_BRANCH: main
          DEPLOYMENT_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd th-ws
          git config --global user.email ength091902@github.com
          git config --global user.name "${{ github.actor }}"
          yarn deploy
