name: Build and Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Fetch the repository code

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20  # Use Node.js version 20

    - name: Install dependencies
      run: |
        cd th-ws  # Navigate to the 'th-ws' directory where the package.json is located
        yarn install  # Install dependencies using yarn

    - name: Build the website
      run: |
        cd th-ws  # Ensure you're in the 'th-ws' directory
        yarn build  # Build the Docusaurus site

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd th-ws  # Navigate to the 'th-ws' directory again
        git config --global user.email ength091902@gmail.com
        git config --global user.name tianhom0919
        GIT_USER=tianhom0919 yarn deploy  # Deploy the built site
