name: Build and Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Fetch the repository code

    - name: Build the website
      run: |
        cd th-ws  # Navigate to the 'th-ws' directory
        yarn build  # Build the Docusaurus site

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd th-ws  # Navigate to the 'th-ws' directory
        GIT_USER=tianhom0919 yarn deploy  # Deploy the built site
