name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install Dependencies
      run: |
        cd th-ws
        yarn install

    - name: Build Website
      run: |
        cd th-ws
        yarn build

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd th-ws
        git config --global user.email ength091902@gmail.com
        git config --global user.name tianhom0919
        GIT_USER=tianhom0919 yarn deploy
